"""Make torneo_id non-nullable in Partido

Revision ID: 40599fcf8f5c
Revises: 78b8e4885a69
Create Date: 2024-10-05 21:30:46.560525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40599fcf8f5c'
down_revision = '78b8e4885a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###