"""Create initial tables

Revision ID: 4320dcbd7824
Revises: 16749cd3abde
Create Date: 2024-10-05 21:08:41.985336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4320dcbd7824'
down_revision = '16749cd3abde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jugadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('nacionalidad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jugadores_apellido'), 'jugadores', ['apellido'], unique=False)
    op.create_index(op.f('ix_jugadores_id'), 'jugadores', ['id'], unique=False)
    op.create_index(op.f('ix_jugadores_nombre'), 'jugadores', ['nombre'], unique=False)
    op.create_table('torneos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('ubicacion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_torneos_id'), 'torneos', ['id'], unique=False)
    op.create_index(op.f('ix_torneos_nombre'), 'torneos', ['nombre'], unique=False)
    op.create_table('parejas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jugador1_id', sa.Integer(), nullable=True),
    sa.Column('jugador2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jugador1_id'], ['jugadores.id'], ),
    sa.ForeignKeyConstraint(['jugador2_id'], ['jugadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parejas_id'), 'parejas', ['id'], unique=False)
    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(), nullable=True),
    sa.Column('cancha', sa.String(), nullable=True),
    sa.Column('horario_inicio_cancha', sa.String(), nullable=True),
    sa.Column('hora_local_actual', sa.String(), nullable=True),
    sa.Column('horario', sa.String(), nullable=True),
    sa.Column('tipo_horario', sa.String(), nullable=True),
    sa.Column('round', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('hora_buenos_aires', sa.String(), nullable=True),
    sa.Column('sets1', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('sets2', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('horario_inicio_cancha_utc', sa.DateTime(), nullable=True),
    sa.Column('hora_local_actual_utc', sa.DateTime(), nullable=True),
    sa.Column('hora_buenos_aires_utc', sa.DateTime(), nullable=True),
    sa.Column('es_despues_partido_anterior', sa.Boolean(), nullable=True),
    sa.Column('torneo_id', sa.Integer(), nullable=True),
    sa.Column('equipo1_id', sa.Integer(), nullable=True),
    sa.Column('equipo2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipo1_id'], ['parejas.id'], ),
    sa.ForeignKeyConstraint(['equipo2_id'], ['parejas.id'], ),
    sa.ForeignKeyConstraint(['torneo_id'], ['torneos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partidos_id'), 'partidos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partidos_id'), table_name='partidos')
    op.drop_table('partidos')
    op.drop_index(op.f('ix_parejas_id'), table_name='parejas')
    op.drop_table('parejas')
    op.drop_index(op.f('ix_torneos_nombre'), table_name='torneos')
    op.drop_index(op.f('ix_torneos_id'), table_name='torneos')
    op.drop_table('torneos')
    op.drop_index(op.f('ix_jugadores_nombre'), table_name='jugadores')
    op.drop_index(op.f('ix_jugadores_id'), table_name='jugadores')
    op.drop_index(op.f('ix_jugadores_apellido'), table_name='jugadores')
    op.drop_table('jugadores')
    # ### end Alembic commands ###