"""Make torneo_id non-nullable in Partido

Revision ID: 78b8e4885a69
Revises: cdfd2b0c00e0
Create Date: 2024-10-05 21:30:30.292717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b8e4885a69'
down_revision = 'cdfd2b0c00e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partidos', 'torneo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partidos', 'torneo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###