"""Update models

Revision ID: a32e94b86178
Revises: 40599fcf8f5c
Create Date: 2024-10-06 01:52:49.515556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32e94b86178'
down_revision = '40599fcf8f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###