"""Make equipo1_id and equipo2_id nullable

Revision ID: cdfd2b0c00e0
Revises: 4320dcbd7824
Create Date: 2024-10-05 21:14:48.951987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdfd2b0c00e0'
down_revision = '4320dcbd7824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###